services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.production
    command: gunicorn configuration.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/home/app/server/static
      - media:/home/app/server/media
    expose:
      - 8000
    env_file:
      - ./.env.production
    depends_on:
      - database
  database:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env.production.database
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/server/static
      - media:/home/app/server/media
    ports:
      - 1337:80
    depends_on:
      - server
volumes:
  data:
  static:
  media: